"""
LLM use quantification based on:
Mapping the Increasing Use of LLMs in Scientific Papers
https://github.com/Weixin-Liang/Mapping-the-Increasing-Use-of-LLMs-in-Scientific-Papers

Estimates the fraction (alpha) of text in a corpus that has been substantially
modified or generated by AI, using distributional GPT detection (population-level).
"""
from .estimation import estimate_text_distribution
from .mle import MLE
from .tokenize import tokenize
from .quantify import quantify_llm_use

__all__ = [
    "estimate_text_distribution",
    "MLE",
    "tokenize",
    "quantify_llm_use",
]
