"""
High-level function to quantify LLM use in a corpus.
"""
import tempfile
import pandas as pd
from pathlib import Path
from typing import Optional, Union, List, Tuple

from .mle import MLE
from .estimation import estimate_text_distribution
from .tokenize import tokenize


def quantify_llm_use(
    inference_data: Union[str, pd.DataFrame, List[str]],
    distribution_path: Optional[str] = None,
    human_parquet_path: Optional[str] = None,
    ai_parquet_path: Optional[str] = None,
    distribution_save_path: str = "distribution.parquet",
    n_bootstrap: int = 1000,
    text_column: Optional[str] = None,
    exploded_data: bool = False,
) -> Tuple[float, float]:
    """
    Quantify the extent of LLM use (alpha) in a corpus.

    Alpha = estimated fraction of text substantially modified or generated by AI.
    Uses distributional GPT detection (population-level, not instance-level).

    Parameters:
        inference_data: One of:
            - Path to parquet with 'inference_sentence' column (list of words per row)
            - DataFrame with 'inference_sentence' column
            - List of raw text strings (abstracts) - will tokenize; set text_column if using DataFrame
        distribution_path: Path to pre-computed distribution parquet.
            Required if human_parquet_path and ai_parquet_path are not provided.
        human_parquet_path: Parquet with human-generated text ('human_sentence' column).
            Used to build distribution if distribution_path is None.
        ai_parquet_path: Parquet with AI-generated text ('ai_sentence' column).
            Used to build distribution if distribution_path is None.
        distribution_save_path: Where to save distribution when building from human+AI data.
        n_bootstrap: Bootstrap samples for CI (default 1000).
        text_column: If inference_data is DataFrame with raw text, column name for text.
        exploded_data: If True, inference parquet already has one sentence per row.

    Returns:
        (estimated_alpha, half_width_of_95_CI)

    Example:
        >>> alpha, ci = quantify_llm_use(
        ...     "target_abstracts.parquet",
        ...     distribution_path="distribution/CS.parquet",
        ... )
        >>> print(f"Estimated LLM use: {alpha:.1%} ± {ci:.1%}")
    """
    # Resolve distribution
    if distribution_path is None:
        if human_parquet_path is None or ai_parquet_path is None:
            raise ValueError(
                "Provide distribution_path OR both human_parquet_path and ai_parquet_path"
            )
        estimate_text_distribution(
            human_parquet_path,
            ai_parquet_path,
            save_file_path=distribution_save_path,
        )
        distribution_path = distribution_save_path

    model = MLE(distribution_path)

    # Prepare inference data
    if isinstance(inference_data, str):
        if not Path(inference_data).exists():
            raise FileNotFoundError(inference_data)
        # Parquet path - MLE.inference expects file path
        return model.inference(
            str(inference_data),
            exploded_data=exploded_data,
            n_bootstrap=n_bootstrap,
        )


    if isinstance(inference_data, pd.DataFrame):
        df = inference_data.copy()
        if text_column is not None:
            # Tokenize raw text
            nlp = None
            try:
                import spacy
                nlp = spacy.load("en_core_web_sm")
            except OSError:
                import spacy
                nlp = spacy.load("en_core_web_sm")
            sentences = df[text_column].apply(
                lambda t: tokenize(str(t) if pd.notna(t) else "", nlp=nlp)
            )
            # Explode: one row per sentence
            df["inference_sentence"] = sentences
            df = df.explode("inference_sentence")
            df = df[df["inference_sentence"].apply(len) > 1]
        if "inference_sentence" not in df.columns:
            raise ValueError("Need inference_sentence or text_column")
        # Save to temp parquet and run inference
        tmp_path = Path(tempfile.gettempdir()) / "llm_quantify_inference.parquet"
        df[["inference_sentence"]].to_parquet(str(tmp_path), index=False)
        return model.inference(
            str(tmp_path), exploded_data=True, n_bootstrap=n_bootstrap
        )


    if isinstance(inference_data, list):
        # List of raw text strings
        nlp = None
        try:
            import spacy
            nlp = spacy.load("en_core_web_sm")
        except OSError:
            import spacy
            nlp = spacy.load("en_core_web_sm")
        all_sentences = []
        for text in inference_data:
            sents = tokenize(str(text) if text else "", nlp=nlp)
            all_sentences.extend(sents)
        df = pd.DataFrame({"inference_sentence": all_sentences})
        df = df[df["inference_sentence"].apply(len) > 1]
        tmp_path = Path(tempfile.gettempdir()) / "llm_quantify_inference.parquet"
        df.to_parquet(str(tmp_path), index=False)
        return model.inference(
            tmp_path, exploded_data=True, n_bootstrap=n_bootstrap
        )

    raise TypeError(
        "inference_data must be str (path), DataFrame, or list of strings"
    )
